### ISSUE TITLE
IndexError: index -1 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by LiaSerrano** [xomicsdatascience/CsoDIAq#28]
Hello @CCranney,

It looks like I'm getting a similar issue to issue #25.  I pasted my console below. I'm trying to search a direct infusion DIA data against a human proteome library. 

Thanks!
Lia

Executing process

Enter library dictionary upload:

6 days, 11:20:56.738240

Begin Grouping Scans by m/z Windows:

6 days, 11:20:56.741837

Number of Unpooled MS/MS Query Spectra: 616

Number of Pooled MS/MS Query Spectra/Mz Windows: 550

Begin Pooled Spectra Analysis:

6 days, 11:20:57.721855

Begin FDR Analysis:

6 days, 11:20:57.792408

Begin Correction Process:

6 days, 11:20:59.121492

Traceback (most recent call last):

File "C:\ProgramData\Anaconda3\envs\csod\Scripts\csodiaq-script.py", line 33, in <module>

sys.exit(load_entry_point('csodiaq', 'console_scripts', 'csodiaq')())

File "c:\users\searcher\desktop\cso\csodiaq\csodiaq.py", line 36, in main

cif.perform_spectra_pooling_and_analysis( args['files'][i],

File "c:\users\searcher\desktop\cso\csodiaq\csodiaq_identification_functions.py", line 82, in perform_spectra_pooling_and_analysis

allSpectraMatches.filter_by_corrected_ppm_window(corrected, maccCutoff, histFile)

File "c:\users\searcher\desktop\cso\csodiaq\IdentificationSpectraMatcher.py", line 163, in filter_by_corrected_ppm_window

self.remove_sparse_matches_and_generate_scores()

File "c:\users\searcher\desktop\cso\csodiaq\IdentificationSpectraMatcher.py", line 151, in remove_sparse_matches_and_generate_scores

self.libraryTags, self.queryTags, self.libraryIntensities, self.queryIntensities, self.ppmMatches = [np.delete(x, remove_indices) for x in [self.libraryTags, self.queryTags, self.libraryIntensities, self.queryIntensities, self.ppmMatches]]

File "c:\users\searcher\desktop\cso\csodiaq\IdentificationSpectraMatcher.py", line 151, in <listcomp>

self.libraryTags, self.queryTags, self.libraryIntensities, self.queryIntensities, self.ppmMatches = [np.delete(x, remove_indices) for x in [self.libraryTags, self.queryTags, self.libraryIntensities, self.queryIntensities, self.ppmMatches]]

File "<__array_function__ internals>", line 180, in delete

File "C:\ProgramData\Anaconda3\envs\csod\lib\site-packages\numpy\lib\function_base.py", line 5128, in delete

keep[obj,] = False

IndexError: index -1 is out of bounds for axis 0 with size 0

Process finished.

**Comment by jessegmeyerlab** [comment]
@LiaSerrano do you know what date you installed the package you used? It is possible the updates were not included in the version you have.

**Comment by LiaSerrano** [comment]
@jessegmeyerlab it definitely would have been after 6/30/22

**Comment by jessegmeyerlab** [comment]
> 

OK it should be the new version then

**Comment by jessegmeyerlab** [comment]
@CCranney any idea why we would be seeing this again with the fix you already made?

**Comment by CCranney** [comment]
Hi @LiaSerrano and @jessegmeyerlab, sorry for the delay. My sister got married last week, and I've fallen behind on everything, including emails. I'll look this over in the next 48 hours and get back to you on it

**Comment by jessegmeyerlab** [comment]
@LiaSerrano it might help us reproduce your error if you can share your library and spectra file. You could email me a link if you don't want it in public

**Comment by jessegmeyerlab** [comment]
Also congratulations to your sister and family Caleb!

**Comment by jessegmeyerlab** [comment]
For the record, Lia let me know that she was using this library from massive https://urldefense.com/v3/__https://massive.ucsd.edu/ProteoSAFe/static/massive-kb-libraries.jsp__;!!KOmnBZxC8_2BBQ!yZs5oTW2aPVEh1EAbLTvROu7mdvo3aY2cc7TIKP5M0kJTD3YtWWFhtaIMc0-bl0T9bgBmvJjY2RbE57XoCDd$

**Comment by jessegmeyerlab** [comment]
Trying to capture the email discussion here in case others have this problem in the future:

From Lia:

Using the TraML library fixed the problem! I got outputs, however the cosine scores are all 0 and I got this error--

 
```

Traceback (most recent call last):

  File "C:\ProgramData\Anaconda3\envs\csod\Scripts\csodiaq-script.py", line 33, in <module>

 

    sys.exit(load_entry_point('csodiaq', 'console_scripts', 'csodiaq')())

  File "c:\users\searcher\desktop\cso\csodiaq\csodiaq.py", line 48, in main

 

    cif.write_fdr_outputs(outFile, spectralFile, peptideFile, proteinFile)

  File "c:\users\searcher\desktop\cso\csodiaq\csodiaq_identification_functions.py", line 105, in write_fdr_outputs

    verifiedProteinDict = idp.find_valid_proteins(peptideProteinConnections)

 File "c:\users\searcher\desktop\cso\csodiaq\idpicker.py", line 222, in find_valid_proteins

    data = group_nodes_with_same_edge(data)

  File "c:\users\searcher\desktop\cso\csodiaq\idpicker.py", line 23, in group_nodes_with_same_edge

 

    if first: l1, l2 = map(list,zip(*data))

ValueError: not enough values to unpack (expected 2, got 0)

 

Process finished.
```

 

 

Do you suspect the scores truly are 0? Is there some sort of correction I can disable that can give me the raw calculation potentially?


@LiaSerrano can you share an example file so we can reproduce the error?
